config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  require 'sidetiq/web'
  
  mount Sidekiq::Web => '/sidekiq'

  root 'employees#index'

  get 'employees/index'

  get 'employees/new'

  post 'employees/create'

  get 'employees/show/:emp_id', to: 'employees#show', as: 'employees_show'

  get 'employees/edit/:emp_id', to: 'employees#edit', as: 'employees_edit'

  patch 'employees/update/:emp_id', to: 'employees#update', as: 'employees_update'

  delete 'employees/destroy/:emp_id', to: 'employees#destroy', as: 'employees_destroy'

  

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :designation, presence: true
  validates :mentor, presence: true
  mount_uploader :profile_image, ProfileImageUploader

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :find_employee, only: [:edit, :update, :destroy]
  
  #--
  # Purpose :- To get all Employees records
  #++ 
  def index
    @emp = Employee.all 
    @emp = @emp.like(params[:filter]) if params[:filter]
  end
  
  def new
    @emp = Employee.new 
  end

  def show    
    @emp = Employee.find(params[:emp_id])
  end
  
  #--
  # Purpose :- To  create employee
  #++  
  def create
    @emp = Employee.new(employee_params)
    if @emp.valid?
      @emp.save
      EmployeesWorker.perform_async(@emp.id)
      render 'show'
    else
      render 'new'
    # purpose:- To show Errors when validations fails on any attribute.
    end
  end
  
  #--
  # Purpose :- To update created employees
  #++
  def update
    @emp.update(employee_params)
    if @emp.valid?
      render 'show'
    else
      render 'new'
      #purpose:- To show Errors when validations fails on any attribute.
    end
  end


  #--
  # Purpose :- To Delete created employees
  #++
  def destroy
    @emp.destroy
    redirect_to root_path
  end

  private
 
    #--
    # Purpose :- To find created employees
    #++
    def find_employee
      @emp = Employee.find(params[:emp_id]) 
    end

    #--
    # Purpose :- To provide strong parameter for creating and updating Employee
    #++
    def employee_params
      params.require(:employee).permit(:name, :email, :designation, :mentor, :profile_image, :profile_image_cache, :remove_profile_image, :remote_profile_image_url)
    end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_errors.html.erb
<% if @emp.errors.any? %>
       <div id="error_explanation">
         <div class="alert alert-danger">
         <ul>
          <% @emp.errors.full_messages.each do |msg| %>
            <li> <%= msg %></li>
          <% end %>
         </ul>
          </div>
        </div>
<% end %>

app/views/employees/_form.html.erb
<div class="form">
  <h3> Employee Details </h3>
    <%= simple_form_for @emp, url: @emp.new_record? ? employees_create_path : employees_update_path(emp_id: @emp.id), :html => {:multipart => true} do |f| %>
      <%= render "errors" %>

        <%= f.input :name,:placeholder => " Enter name here.", required: true %><br>
         
        <%= f.input :email,:placeholder => " me@exaple.com ", type: :email %><br>

        <%= f.input :designation,:placeholder => " Enter Designation here.", required: true %><br>

        <%= f.input :mentor, required: true %><br>

        <p>
        <%= image_tag(@emp.profile_image_url) if @emp.profile_image? %>

        <%= f.input :profile_image, required: true %>

        <%= f.hidden_field :profile_image_cache %></p><br>

        <p> <% if @emp.profile_image_cache.present? %>
          <%= f.input :remove_profile_image, as: :boolean, checked_value: true, unchecked_value: false %>
            <% end %>
        </p>
        OR CHOOSE REMOTE URL
        <p>
        <%= f.input :remote_profile_image_url %>
        </p><br>

        <br><%= f.button :submit, class: "btn btn-primary"%>

     <% end %>
</div>

app/views/employees/create.html.erb
<h1>Employees#create</h1>
<p>Find me in app/views/employees/create.html.erb</p>

app/views/employees/edit.html.erb
<%= render "form" %>

app/views/employees/index.html.erb
<!-- <h3> Search Empolyee </h3>
  <%#= form_tag employees_index_path,:method=>'get' do %>
    <p>
      <%#= text_field_tag :filter, '', placeholder: "Search...", autocomplete: :off %>
      <button class="btn btn-primary disabled" type="submit">S E A R C H</button>
    </p>
  <%# end %> -->

  <td> <%= link_to "ADD Employee",employees_new_path %></td>
<table class="table table-striped table-hover ">
  <thead>
    <tr class="info">
      <th> Image </th>
      <th> Name </th>
      <th> Email</th>
      <th> Designation </th>
      <th> Mentor </th>
      <th> Edit</th>
      <th> Delete</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @emp.each do |e| %>
      <tr>
        <td><%= link_to image_tag(e.profile_image_url(:thumb)),employees_show_path(e) %></td>
        <td> <%= e.name %> </td>
        <td> <%= e.email %> </td>
        <td> <%= e.designation %> </td>
        <td> <%= e.mentor %> </td>
        <td> <%= link_to "Edit",employees_edit_path(e) %></td>
        <td> <%= link_to "Delete",employees_destroy_path(e), method: :delete, data: { confirm:'are u sure?' } %></td>
      </tr>
    <% end %>  

  </tbody>
</table>

app/views/employees/new.html.erb
<%= render "form" %>

app/views/employees/show.html.erb
<p>Employee Details</p>

<p>Employee Profile Image : <%= image_tag @emp.profile_image_url(:gallary) %></p>
<p>Employee Name : <%= @emp.name %></p>
<p>Employee Email : <%= @emp.email %></p>
<p>Employee Designation : <%= @emp.designation %></p>
<p>Employee Mentor : <%= @emp.mentor %></p>




<%= link_to "BACK", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmployeeManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>